#!/usr/bin/env node
/**
 * Regenerate frontend + mobile legal exports from shared/legal/*.md
 * Usage: node scripts/sync-legal.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SHARED = path.join(ROOT, 'shared', 'legal');

const FILES = [
  { md: 'privacy.md', export: 'PRIVACY_MD' },
  { md: 'terms.md', export: 'TERMS_MD' },
  { md: 'contact.md', export: 'CONTACT_MD' },
];

function escapeForTemplateLiteral(content) {
  return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function buildModule(exports) {
  const header =
    '// AUTO-GENERATED by scripts/sync-legal.js — do not edit by hand.\n' +
    '// Source of truth: TrimiT/shared/legal/{privacy,terms,contact}.md\n\n';
  const body = exports
    .map(({ name, content }) => `export const ${name} = \`${escapeForTemplateLiteral(content)}\`;\n`)
    .join('\n');
  return header + body;
}

function readMd(filename) {
  const filePath = path.join(SHARED, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing ${filePath}`);
  }
  return fs.readFileSync(filePath, 'utf8').trimEnd() + '\n';
}

const legalExports = FILES.map(({ md, export: exportName }) => ({
  name: exportName,
  content: readMd(md),
}));

const moduleSource = buildModule(legalExports);

const targets = [
  path.join(ROOT, 'frontend', 'src', 'legal', 'content.js'),
  path.join(ROOT, 'mobile', 'src', 'legal', 'content.ts'),
];

for (const target of targets) {
  fs.writeFileSync(target, moduleSource, 'utf8');
  console.log(`Wrote ${path.relative(ROOT, target)}`);
}

console.log('Legal sync complete.');
